format_version: 3
pipelines:
  springbootwebapp-ci:
    lock_behavior: lockOnFailure
    group: SPRINGBOOTWEBAPP
    materials:
      repo: 
       git: https://github.com/EscarlethFatima/EL_springbootwebapp.git
       branch: gocd-yml-updated
    stages: 
      - Build:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: jar/
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml
                - test:
                    source: build/reports/jacoco/**/*
                    destination: jacoco_report                 
              tabs:
                unit_test: html/index.html
                jacoco_report: jacoco_report/index.html 
      - CodeQuality:
          jobs:
            sonarqube:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - check
                      - sonarqube
                      - "-Dsonar.organization=escarlethfatima-github"
                      - "-Dsonar.host.url=https://sonarcloud.io"
                      - "-Dsonar.projectKey=my:project155"
              artifacts:
                - build:
                    source: build/reports/findbugs/*.html
                    destination: findbugs
                - build:
                    source: build/reports/pmd/*.html
                    destination: pmd
              tabs:
                findbugs: findbugs/main.html
                pmd: pmd/main.html
      - Package:
          jobs:
            package-jar:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:                      
                      - build
                      - capsule   
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: package
      - Deploy:
          jobs:
            deploy-jar:
              tasks:
                - fetch:
                    stage: Build
                    job: building
                    source: jar/
                - exec:
                    command: ./gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.216
                      - -Puser_server=ubuntu
                      - -Pkey_path=/home/go/devops.pem
                      - -Pjar_path=jar/
                      - -Pjar_name=spring-boot-web-0.0.1-SNAPSHOT-capsule

